#! /usr/bin/env python3

from colorama import Style
from colorama import Fore as tc
import sys
import shlex

arguments = sys.argv
if len(arguments) != 2:
    print(tc.RED + "USAGE: cobra <file_path.coil>" + Style.RESET_ALL)
    exit(1)
elif not arguments[1].endswith(".coil"):
    print(tc.RED + "You can only run .coil scripts made for Cobra." + Style.RESET_ALL)
    exit(1)

def loadFile(source):
    with open(source, "r") as file:
        return file.readlines()

class cobra:
    def __init__(self):
        self.commands = {
            "show": self.show,
            "let": self.let
        }
        self.variables = {}
        self.variableTypes = [
            "int", "str"
        ]

    def show(self, arguments):
        if len(arguments) == 2:
            text = self.isString(arguments[0], mode=2)
            if text is False:
                self.throwError("STRING ARGUMENTS MUST BE WRAPPED IN DOUBLE QUOTES.")
            raw_color = arguments[1]
            color_name = self.isString(raw_color, mode=2)
            if color_name is False:
                color_name = raw_color
            else:
                self.throwError("EXPECTED COLOR CONSTANT, GOT STRING")

            color = self.convertStringToColor(color_name) # You did it. You avoided all the errors, provided all the right arguments, and used correct syntax. You printed a message to the console. A winner is you. #
            print(color + text + Style.RESET_ALL)

        elif len(arguments) == 1:
            text = self.isString(arguments[0], mode=2)
            if text is False:
                self.throwError("STRING ARGUMENTS MUST BE WRAPPED IN DOUBLE QUOTES.")
            print(text)
        else:
            self.throwError(f"KEYWORD SHOW REQUIRES 1, TAKES 2 ARGUMENTS, {len(arguments)} GIVEN.")

    def convertStringToColor(self, string: str):
        if string.lower() == "red":
            return tc.RED
        elif string.lower() == "blue":
            return tc.BLUE
        elif string.lower() == "green":
            return tc.GREEN
        elif string.lower() == "yellow":
            return tc.YELLOW
        elif string.lower() == "purple":
            return tc.MAGENTA
        elif string.lower() == "cyan":
            return tc.CYAN
        
    def let(self, arguments):
        if len(arguments) != 4:
            self.throwError(f"KEYWORD LET REQUIRES 3 ARGUMENTS, {len(arguments) - 1} GIVEN.")
        else:
            type = arguments[0]
            if type not in self.variableTypes:
                self.throwError(f"INVALID TYPE {type}. VALID TYPES: {', '.join(self.variableTypes)}")
            name = arguments[1]
            if name in self.variables:
                self.throwError(f"VARIABLE ALREADY DECLARED: {name}")
            operator = arguments[2]
            value = arguments[3]
            if operator != "=":
                self.throwError(f"INVALID OPERATOR {operator}. EXPECTED: '='")
            match type:
                case "int":
                    if value.isdigit():
                        self.variables[name] = int(value)
                    else:
                        self.throwError(f"TRIED TO DECLARE VARIABLE TYPE INT, BUT WAS NOT FULLY NUMBERS")
                case "str":
                    if value.startswith("\"") and value.endswith("\""):
                        self.variables[name] = value
                    else:
                        if value in self.variables:
                            source_value = self.variables[value]
                            if isinstance(source_value, str):
                                self.variables[name] = source_value
                            else:
                                self.throwError(f"TRIED TO DECLARE VARIABLE TYPE STR, BUT SOURCE VARIABLE {value} IS NOT TYPE STR.")
                        else:
                            self.throwError(f"TRIED TO DECLARE VARIABLE TYPE STR, BUT VALUE WAS NOT WRAPPED IN DOUBLE QUOTES.")
    
    def throwError(self, message="THERE WAS AN UNEXPECTED ERROR.", color=tc.RED):
        msg = "ERROR!\n\n" + message + "\n\nERROR!"
        print(color + msg + Style.RESET_ALL)
        exit(1)
    
    def isString(self:cobra, string: str, mode:int=1):
        if mode == 1: # Mode 1: returns a boolean. (is it wrapped in double quotes)
            if string.startswith("\"") and string.endswith("\""):
                return True
            return False
        elif mode == 2: # Mode 2: returns a python string. (strips the original str of its quotes)
            if string.startswith("\"") and string.endswith("\""):
                return string[1:len(string)-1]
            return False
    

src = arguments[1]
scriptlines = loadFile(src)

def main():
    global scriptlines
    currentline = 0 
    Cobra = cobra()
    
    for line in scriptlines:
        currentline += 1
        line = line.strip()
        if line != "":
            if line.startswith("#" or "//"):
                continue
            try:
                sectors = shlex.split(line, posix=False)
            except ValueError:
                Cobra.throwError(f"Error parsing at line {currentline}", Cobra.convertStringToColor("purple"))

            filtered_sectors = [] # yes, i ripped this straight out of old cobra.
            for s in sectors:
                if s.startswith("//") or s.startswith("#"):
                    break  # Ignore everything after this
                filtered_sectors.append(s)
            if not filtered_sectors:
                continue

            command = filtered_sectors[0]
            arguments = filtered_sectors[1:]

            # --- DEBUG --- #
            #print("Sectors:", sectors)
            #print("Command:", command)
            #print("Arguments:", arguments)
            #print("Current Line:", currentline)

            


            if command in Cobra.commands:
                #print("Command found.") # --- DEBUG --- #
                Cobra.commands[command](arguments)
        else:
            continue

if __name__ == "__main__":
    main()
