#! /usr/bin/env python3

from colorama import Style
from colorama import Fore as tc
import sys
import shlex

arguments = sys.argv
if len(arguments) != 2:
    print(tc.RED + "USAGE: cobra <file_path.coil>" + Style.RESET_ALL)
    exit(1)
elif not arguments[1].endswith(".coil"):
    print(tc.RED + "You can only run .coil scripts made for Cobra." + Style.RESET_ALL)
    exit(1)

def loadFile(source):
    with open(source, "r") as file:
        return file.readlines()

class cobra:
    def __init__(self):
        self.commands = {
            "show": self.show
        }
    def show(self, arguments):
        if len(arguments) > 1:
            print(arguments[1] + arguments[0])
        else:
            print(arguments[0])

src = arguments[1]
scriptlines = loadFile(src)

def main():
    global scriptlines
    Cobra = cobra()
    
    for line in scriptlines:

        line = line.strip()
        sectors = shlex.split(line)
        command = sectors[0]
        arguments = sectors[1:]

        # --- DEBUG --- #
        #print(sectors)
        #print(command)
        #print(arguments)


        if command in Cobra.commands:
            #print("Command found.") # --- DEBUG --- #
            Cobra.commands[command](arguments)

if __name__ == "__main__":
    main()

